### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by webchaz** [localnerve/html-snapshots#37]
I keep getting `timed out waiting for #viewContent to become visible for http://localhost:5000/` when trying snapshots on an angular app.  The id `viewContent` is loaded in the `ng-view` and the site loads quickly, total latency is less than 200ms and I have the default timeout set.

The error I get back in response is just `true`.  Any ideas why this wouldn't recognize the id? I tried also removing the ID and this did the same thing.  When I inspect the source of the page, everything is right with the ID loaded.  Any ideas?

Thank you

**Comment by webchaz** [comment]
Ok, this seems to be an issue with typekit, which I have being loaded.  Does phantom forward IP address or use local ip address? typekit has an allow-list for host IP's, otherwise it timesout for a while and then returns 401.

**Comment by localnerve** [comment]
Do you have to make your selector dependent on typekit?
I assume the source ip address is the ip address of the host you are running this on.
Also, remember that the timeout is for the total, per-process snapshot processing time. This will include PhantomJS processing time. It will take longer than the latency of your site.
If you want me to look further, post your options and let me run the snapshots against your site.

**Comment by localnerve** [comment]
Do you need help with this or want to suggest a change?
Please let me know so the ticket can be settled, thank you.

**Comment by webchaz** [comment]
Hello, Sorry for the delayed response.  It was definitely related to typekit.  Their script is funky, has a lot of authentication, maybe it was blocking the headers or agent, I don't know.  But when it does, it takes a long time to return a 401.   But it works just as expected without, so I think this can be closed.  I just removed typekit, which is fine.

**Comment by localnerve** [comment]
OK, thanks.
I was curious if you tried making the typekit download asynchronous. This would have prevented blocking, allowed the browser to render to continue (presumably), and your selectors to be evaluated in a more reasonable amount of time.
I would imagine that would be preferable code for you regardless of the browser (PhantomJS or not).
Just curious.

**Comment by webchaz** [comment]
Ah good thought, I didn't realize they had async version.  Just tried it out, but still got the same issue.  Timeout on typekit was set to 1000 and default on snapshots.

**Comment by localnerve** [comment]
That is unexpected.
I wonder if PhantomJS 2 honors this better.
That would be good to see, raise the urgency for moving to 2.x...
