### ISSUE TITLE
canonical url not appearing in generated html file

### ISSUE THREAD

**Issue by CloudHadoop** [localnerve/html-snapshots#42]
canonical url not appearing in generated html file.

Please let me know what option i need to supply to include rel canonical url in generated html snapshot

**Comment by localnerve** [comment]
To my knowledge, there is no filter in this software that would remove such a thing from the snapshot. Are you supplying a custom filter?
Is there a public site I can use to reproduce the error?

**Comment by localnerve** [comment]
Hello @CloudHadoop , I haven't heard back from you.
Is the canonical url in the source output, or is this something you wanted to add after the fact?

**Comment by localnerve** [comment]
Closing since I haven't heard back in 3 weeks. Feel free to reopen to continue.
