### ISSUE TITLE
meta tag removing

### ISSUE THREAD

**Issue by dpocheketa** [localnerve/html-snapshots#44]
Hi, regarding this article https://developers.google.com/webmasters/ajax-crawling/docs/getting-started
`<meta name="fragment" content="!">`
should be only in original web-pages with Ajax content. Is it possible to add some option for removing meta tags like this from output?

**Comment by localnerve** [comment]
This is achieved using a custom filter.

[See example](https://github.com/localnerve/html-snapshots/tree/master/examples/custom)
[See doc](https://github.com/localnerve/html-snapshots/blob/master/README.md#snapshot-control-options), subsection of importance is under `snapshotScript` bullet.

**Comment by dpocheketa** [comment]
Thank you. It is work for me.
