### ISSUE TITLE
Selector added by ajax script doesn't fire snapshot

### ISSUE THREAD

**Issue by codekraft-studio** [localnerve/html-snapshots#46]
I've this case where when the page loads it fire a ajax request using some parameters passed with #! and then, once has done it adds a `div#rmp-done`, I set up htmlSnapshots like this to wait for that selector:

```javascript
var htmlSnapshots = require('html-snapshots');
var result = htmlSnapshots.run({
	input: "array",
	source: [
		"mysite/something/#!/first_param"
	],
	outputDir: "./snapshots",
	outputDirClean: true,
        selector: "#rmp-done"
});
```
but I wait a lot and then fails with no output.

The javascript file is a simple jQuery script that call $.ajax to an url and fetch some data then once has done it append the data and __div#rmp-done__ to the body.

Is possible to do trigger the snapshot when the ajax call has finished? (with a timeout callback works fine)

**Comment by localnerve** [comment]
Interesting. Is there a public endpoint a can try against?

**Comment by codekraft-studio** [comment]
@localnerve 
yes for sure, this is the page i'm trying with: https://www.ecutuningperformance.com/en/chip-tuning/#!/ALFA-ROMEO/147/1.6L-16V-TS-88KW-120PS-ME7.3.1
in this particular page there is a script wich takes the hash params and build the results (after an ajax call)

the selector i'm waiting for is: __rmp-done__ is appended after all at the bottom of the body.

By the way is a __great tool__, I've tried it a lot and is working very good, but I would suggest more verbosity specially when it fails for timeout or something else, or even the count of the failed snapshots.

**Comment by localnerve** [comment]
OK, I found the reason:
It actually does find the rmp-done element but it is deemed [not visible](https://github.com/localnerve/html-snapshots/blob/master/docs/notes.md#why-visible) b/c there is no visible content.

[More precisely, no width/height](https://github.com/localnerve/html-snapshots/blob/master/lib/phantom/modules/detectors.js#L29)

**Comment by codekraft-studio** [comment]
oh, that's great! when I return home i'll try again.
Also there is an option to watch for a particular selector visibility change to trigger the snapshot?

I'll would like to contribute, I'll fork the project and play with it, I just need to understand which files are doing what. Many thanks again!

**Comment by localnerve** [comment]
Yea, this is extensible already to cover this use case. I'll be available
more later on too .

**Comment by codekraft-studio** [comment]
@localnerve I tried out with a defined width,height but is still not working.
Actually I append this element:
```javascript
$('<div></div>')
.attr('id', 'rmp-done')
.css({width: '100%', height: '20px'})
```
$(document).find('#rmp-done')[0].offsetWidth  and $(document).find('#rmp-done')[0].offsetHeight are defined, so `result = el.offsetWidth && el.offsetHeight;` should return true.
What should I do as best practice to make it working good, the element should contain the text?

Sorry again for the inconvenience.

**Comment by localnerve** [comment]
How I tested was to just insert output statements into the installed code. Quick and dirty results.

If you're interested:
1. Update [selectorDetect.js](https://github.com/localnerve/html-snapshots/blob/9e7b9cc6205255eb58601c76148523475d582bc4/lib/phantom/modules/selectorDetect.js#L73) to receive output from the page and write it out to a test file:
```javascript
        // The test to determine readiness
        function() {
          var testObj = page.evaluate(detector, {
            selector: options.selector,
            url: options.url
          });

          fs.write("test001.txt", testObj.output, "a");
          return testObj.result;
        },
```

2. Collect output in the detector used in [detectors.js](https://github.com/localnerve/html-snapshots/blob/9e7b9cc6205255eb58601c76148523475d582bc4/lib/phantom/modules/detectors.js#L23):
```javascript
  querySelector: function(options) {

    var result = false;
    var el = document.querySelector(options.selector);

    var output = '@@@ querySelector called\n';

    if (el) {
      output += '  => found element, ';

      // el must be an HTMLElement that is visible
      result = el.offsetWidth && el.offsetHeight;

      output += 'result: '+result+'\n';
    }

    return {
      result: result,
      output: output
    };
  },
```

3. I ran this test script:
```javascript
var path = require("path");
var util = require("util");
var assert = require("assert");
var htmlSnapshots = require("html-snapshots");

htmlSnapshots.run({
  input: 'array',
  source: [ 'https://www.ecutuningperformance.com/en/chip-tuning/#!/ALFA-ROMEO/147/1.6L-16V-TS-88KW-120PS-ME7.3.1' ],
  outputDir: path.join(__dirname, "./tmp"),
  outputDirClean: true,
  selector: '#rmp-done',
  timeout: 30000
}, function(err, completed) {

  console.log("completed snapshots:");
  console.log(util.inspect(completed));

  // throw if there was an error
  assert.ifError(err);
});
```

4. Open 'test001.txt':
```
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
@@@ querySelector called
  => found element, result: 0
@@@ querySelector called
  => found element, result: 0
@@@ querySelector called
  => found element, result: 0
@@@ querySelector called
  => found element, result: 0
@@@ querySelector called
  => found element, result: 0
@@@ querySelector called
  => found element, result: 0
// A bunch more repeating I'm omitting
```

**Comment by localnerve** [comment]
BTW, You also have lots of other options here:
1. Add an attribute or class to the body (or more appropriate element) when done (in lieu of an empty/faux div).
2. Write a snapshotScript of your own that doesn't consider visibility.

**Comment by codekraft-studio** [comment]
Many thanks for the tips! I will spent time on it!
After seeing strange things on my windows machine I decided to try on a linux based environment and I realized is a lot verbose and I really don't know why but on windows was behaving strangely :[ that's why previously I suggested for more verbosity because the same script wasn't returning anything as output when I was trying on windows.
Also there was a couple of bugs (maybe related to my windows environment) once is this:
```javascript
rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\temp'
    at Error (native)

    at Object.fs.rmdirSync (fs.js:806:18)
    at rmkidsSync (C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\node_modules\rimraf\rimraf.js:303:9)
    at Object.module.exports.run (C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\node_modules\html-snapshots\lib\html-snapshots.js:129:7)
    at Object.<anonymous> (C:\Users\Filippo\Desktop\templates\temp\etp_snapshot\main.js:7:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```
after opening a snapshot with a editor to watch it.

And when I used an array of sources, it always did one and no more. (always on windows), in linux the same script run through all of them.
```javascript
source: [
	"http://www.codekraft.it/test/index#!test",
	"http://www.codekraft.it/test/index#!prova",
	"http://www.codekraft.it/test/index",
],
```
```javascript
node main.js
completed snapshots:
[ 'temp\\test\\index#!prova\\index.html' ]
```
In linux is working like a charm I will continue on this. 
Many many thanks __great package :package: __ again!!
