### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by glebmachine** [localnerve/html-snapshots#50]
I have issue with error handling.

Case:
I've got 10ms timeout, which cause this error ```PhantomJS error: timed out waiting for html``` 

Problem
1. Promise resolving ```then``` _before_ error is thrown by PhantomJS.
2. Callback triggers with _empty error_ argument.

Also, node process finished w/o errors:
```bash
echo $?
> 0
```

How do i properly catch errors?

**Comment by localnerve** [comment]
Can you please provide the options you're using and an endpoint for me to duplicate?

**Comment by localnerve** [comment]
I can't reproduce, so I'm closing this issue due to lack of correspondence. If you can supply the options you used to produce the condition, please re-open and post the options so this can be fixed.
