### ISSUE TITLE
A delay before generate snapshot by phantomjs

### ISSUE THREAD

**Issue by samialmorshedi** [localnerve/html-snapshots#65]
I configured my app like this:
`input: "array",
      source: sitemap,
      outputDir: "./snapshots",
      outputDirClean: true,
      selector: {
        "__default": "body"
      },  
      timeout: {
        "__default": 10000
      }`

And my app is using Angularjs 1.5. The problem is in some pages, after the page loaded completely, There is another XHR request that will give info from db. I need a small delay before generating snapshot to let the app finish the XHR request. How can I do that?

**Comment by localnerve** [comment]
Does the XHR request result in a change to the html?

**Comment by localnerve** [comment]
Haven't heard back from you in 10 days, so I'm closing. Feel free to reopen if you want help.
