### ISSUE TITLE
[Feature Request] Get html as plain text instead of writing to a file

### ISSUE THREAD

**Issue by JamesJGoodwin** [localnerve/html-snapshots#68]
Hello. I'd like to store my html not as a single file somewhere deep in my system but to store it in DB as plain text. Am I able to access parsed html as soon as parsing process finished and disable writing it to a file? If not then it would be a great feature. Thanks.

**Comment by localnerve** [comment]
You can do this now. Read the other process' files (as temporary output) and stream them to/from storage. Here is an (older) [example w/explanation](https://github.com/localnerve/html-snapshots/blob/master/docs/example-heroku-redis.md) also with code. Example uses a Redis store.

If you propose "fancier" IPC (other than files), it would need to work with phantomjs and chrome.

**Comment by JamesJGoodwin** [comment]
I thought I could use it like that:

```javascript
onSelectorFound: function(html) {
    // 
}
```

The thing is that I'm using html-snapshots automatically when search engine robot detected visiting my website. I call php `exec()` function to run `node html-snapshots.js https://www.example.com` command, but this command runs by user **www-data**(since it was called from the web) and since www-data have no rights to create folders and files I have to do `chown -R www-data:www-data snapshots` to snapshot files start to creating properly. It would've been a really good feature because I could just get html as plain text and put it to my PostgreSQL database via NodeJS instead of using a local storage and wasting free memory on my SSD as well as lowering IOPS.

**Comment by localnerve** [comment]
Here's my thoughts:
1. There's nothing to gain generating the snapshots at request time. You actually get penalized for a render and processing cost that is un-needed. Decouple these things where the requirement does not exist. Pre-render via worker process on an interval into storage (like in the example) to avoid this cost, and get a major TTFB performance boost for search engine robot. Serve to the search engine bot from storage. (The example linked above uses Redis for speed).
2. You can set the temporary output directory anywhere on the FS where permissions work for you.

**Comment by JamesJGoodwin** [comment]
I'll close the issue for now. Thanks for advice!
