### ISSUE TITLE
I see empty folders for all pages in the site map

### ISSUE THREAD

**Issue by mail2jomy** [localnerve/html-snapshots#854]
### Expected Behavior

I see empty folders in the tmp folder, no html or images. 

### Actual Behavior
empy folders not html. My site do not have .html extension on pages.

**Comment by localnerve** [comment]
I'm not clear on what you are saying.

From the html-snapshots project directory, what happens when you:
1. type `cd examples/sitemap-index`
2. type `npm i` 
3. type `npm start`
4. check the output in `examples/sitemap-index/tmp`

**Comment by localnerve** [comment]
closing, non-responsive
